#!/bin/bash
# START_HERE.sh - Quick start script for G-Parking

echo "========================================="
echo "🚗 G-PARKING - Mobile Testing Setup"
echo "========================================="
echo ""
echo "✅ Prerequisites:"
echo "   • Node.js installed (https://nodejs.org)"
echo "   • Phone & PC on same WiFi network"
echo ""
echo "📋 3-Step Quick Start:"
echo ""
echo "Step 1: Install dependencies"
echo "   $ npm install"
echo ""
echo "Step 2: Start server"
echo "   $ npm start"
echo ""
echo "Step 3: Open on mobile"
echo "   • Copy URL from console"
echo "   • Open in phone browser"
echo "   • Done! 🎉"
echo ""
echo "========================================="
echo "📱 Mobile URL Format:"
echo "   http://[YOUR_IP]:3000/parking-en.html"
echo ""
echo "💻 Desktop URL:"
echo "   http://localhost:3000/parking-en.html"
echo "========================================="
echo ""
echo "📖 For detailed help:"
echo "   • Read MOBILE_SETUP.md"
echo "   • Read ENGLISH_MOBILE_READY.md"
echo "   • Check TRANSLATION_COMPLETE.md"
echo ""
echo "Ready? Let's go! 🚀"
echo ""
